Imports System

'Each new term in the Fibonacci sequence is generated by 
'adding the previous two terms. 
'By starting with 1 and 2, the first 10 terms will be:
'1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
'By considering the terms in the Fibonacci sequence 
'whose values do not exceed four million, 
'find the sum of the even-valued terms.

Module Problem2
    Public Function run () As Integer 
        Dim upperBound As Integer = 4000000 
        Dim num1 As Integer = 1
        Dim num2 As Integer = 1
        Dim sum As Integer = 0
        Dim tempNum
            While num2 < upperBound
                Console.WriteLine(num2)
                tempNum = num2
                num2 = num1 + num2
                num1 = tempNum
                    If num2 Mod 2 = 0 Then 
                        sum = sum + num2 
                    End If 
            End While
        Return sum
    End Function
End Module